[package]
name = "libpr4-sys"
version = "0.1.0"
build = "build.rs"
links = "https://archive.org/details/tucows_223698_Power_Render_3D_Engine"
edition = "2021"

[dependencies]
libc = "0.2.144"

[build-dependencies]
cc = "1.0.79"
pkg-config = "0.3.27"
