[package]
name = "mhex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starforcelib = {path = "../starforcelib"}
lightwave-3d = "1.0.0"
glob = "0.3.1"
